file1 = open('school_notice.txt', 'r')
content = file1.read()
print(content)
file1.close()
file2 = open('school_notice.txt', 'a')
file2.write('Above students were absnet on Thursday!!!')
file2.close()
file3 = open('school_notice.txt', 'r')
content = file3.read(15)
print(content)
file3.close()